version: "3.9"

services:
  users:
    build:
      context: .
      dockerfile: services/users/Dockerfile
    container_name: users
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8001"]
    ports:
      - "8001:8001"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

  tasks:
    build:
      context: .
      dockerfile: services/tasks/Dockerfile
    container_name: tasks
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8002"]
    ports:
      - "8002:8002"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    container_name: gateway
    depends_on:
      - users
      - tasks
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8080"]
    ports:
      - "${GATEWAY_PORT:-8080}:8080"
    environment:
      - USERS_SERVICE_URL=${USERS_SERVICE_URL:-http://users:8001}
      - TASKS_SERVICE_URL=${TASKS_SERVICE_URL:-http://tasks:8002}
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

  ui:
    build:
      context: .
      dockerfile: ui/Dockerfile
    container_name: ui
    depends_on:
      - gateway
    command: ["streamlit", "run", "/app/streamlit_app/app.py", "--server.port=8501", "--server.address=0.0.0.0"]
    ports:
      - "${STREAMLIT_PORT:-8501}:8501"
    environment:
      - GATEWAY_URL=http://gateway:8080
      - STREAMLIT_SERVER_PORT=8501
    restart: unless-stopped